<template>
  <div class="loading">
    <div class="loadingio-spinner-spinner-p878j8ju68">
      <div class="ldio-hrs7u6z8yoa">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: "notify",
};
</script>
<style type="text/css">
.loading {
  opacity: 0;
  display: none;
  overflow: visible;
}
.show {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 999;
  opacity: 0.5;
  overflow: hidden;
  background-color: white !important;
}
.loadingio-spinner-spinner-p878j8ju68 {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
@keyframes ldio-hrs7u6z8yoa {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-hrs7u6z8yoa div {
  left: 151.81px;
  top: 67.83px;
  position: absolute;
  animation: ldio-hrs7u6z8yoa linear 0.970873786407767s infinite;
  background: #1d3f72;
  width: 19.38px;
  height: 38.76px;
  border-radius: 9.69px / 19.38px;
  transform-origin: 9.69px 93.67px;
}
.ldio-hrs7u6z8yoa div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.8899676375404532s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8090614886731392s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.7281553398058253s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6472491909385114s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5663430420711975s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.4854368932038835s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4045307443365696s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3236245954692557s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.24271844660194175s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16181229773462785s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08090614886731393s;
  background: #1d3f72;
}
.ldio-hrs7u6z8yoa div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #1d3f72;
}
.loadingio-spinner-spinner-p878j8ju68 {
  width: 323px;
  height: 323px;
  display: inline-block;
  overflow: hidden;
}
.ldio-hrs7u6z8yoa {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-hrs7u6z8yoa div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
